package com.wellsfargo.counselor.entity;

import java.util.ArrayList;
import java.util.List;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
*Represents a financial advisor within a counselor system
*
*<p>
*An {@code Advisor} is responsible for managing one or more {@link Client}
*entities. Each advisor is uniquely identified by an auto-generated ID and 
*has the required personal and contact information
*</p>
*
*<p>
*This entity is mapped to {@code advisor} table in the database.
*</p>
*/
@Entity
@Table(name = "advisor")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Advisor {
	
	/**
	 *  Advisor's unique identifier. This value is automatically generated by the database.
	 */
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "advisor_id")
    private Long advisorId;

	/** Advisor's first name. */
    @NotBlank
    @Column(name = "first_name", nullable = false)
    private String firstName;

	/** Advisor's last name. */
    @NotBlank
    @Column(name = "last_name", nullable = false)
    private String lastName;

	/** Advisor's mailing address. */
    @NotBlank
    @Column(name = "address", nullable = false)
    private String address;

	/** Advisor's contact number. */ 
    @NotBlank
    @Column(name = "phone", nullable = false)
    private String phone;

	/** Advisor's email address. This value must be unique and conforms to a valid email format. */
    @Email
    @Column(name = "email", nullable = false, unique = true)
    private String email;
	
	/**
	* List of clients associated with this advisor.
	* <p> 
	* This represents a one-to-many relationship where one advisor
	* may manage multiple clients
	* </p>
	*/
    @OneToMany(mappedBy = "advisor")
    private List<Client> clients = new ArrayList<>();
}