package com.wellsfargo.counselor.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a client within the counselor system.
 * 
 * <p>
 * A {@code Client} contains personal and contact information and may 
 * optionally be associated with an {@link Advisor}.
 * Each client is uniquely identified by an auto-generated ID.
 *</p>
 *
 * <p>
 * This entity is mapped to the {@code Client} table in the database.
 * </p>
*/

@Entity
@Table(name = "client")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Client {

	/**
	 * Unique Identifier for the client, auto-generated by the database.
	 */
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "client_id")
	private Long clientId;
	
	/** Client's first name. */
	@NotBlank
	@Column(name = "first_name", nullable = false)
	private String firstName;
	
	/** Client's last name. */
	@NotBlank
	@Column(name = "last_name", nullable = false)
	private String lastName;
	
	/** Client's mailing address. */
	@NotBlank
	@Column(name = "address", nullable = false)
	private String address;

	/**	Client's contact number. */
	@NotBlank
	@Column(name = "phone", nullable = false)
	private String phone;

	/** Client's email address. This value must be unique and conforms to a valid email format. */
	@Email
	@Column(name = "email", nullable = false, unique = true)
	private String email;

	/**	
	*The advisor associated with this client.
	*
	*<p>
	*Represents many-to-one relationship; many clients can be 
	*assigned to one advisor.
	*</p>
	*/
	@ManyToOne
	@JoinColumn(name="advisor_id", nullable = true)
	private Advisor advisor;

	/**
	*Constructs a client without assigning an advisor.
	*
	*@param firstName client's first name
	*@param lastName client's last name
	*@param address client's mailing address
	*@param phone client's phone number
	*@param email client's email address
	*/
	public Client(String firstName, String lastName, String address,
				  String phone, String email) {
			this.firstName = firstName;
			this.lastName = lastName;
			this.address = address;
			this.phone = phone;
			this.email = email;
		}
}
