package com.wellsfargo.counselor.entity;

import java.util.List;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** 
 *Represents a portfolio within the counselor system.
 *<p>
	 *A portfolio contains multiple securities and is associated with a single client.
	 *This class is mapped to the portfolio table in the database.
 *</p>
*/
@Entity
@Table(name = "portfolio")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Portfolio {

	/**
	 	* Unique identifier for portfolio, auto-generated by the database. 
	*/
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "portfolio_id")
	private Long portfolioId;

	/**
	 *  Portfolio creation date.
	 * <p>
	 	* Stored as string for database compatibility, cannot be null.
	 * </p>
	 */
	@NotNull
	@Column(name = "creation_date",nullable = false)
	private String creationDate;

	/**
	*List of securities associated with this portfolio.
	*<p>
		*Represents one-to-many relationship; a portfolio can have many securities.
	*</p>
	*/
	@OneToMany(mappedBy = "portfolio")
	private List<Security> securities;

	/**
	*Client associated with this portfolio
	*<p>
		*Represnts many-to-one relationship;many portfolios can belong to a single client.
	*</p>
	*/
	@ManyToOne
	@JoinColumn(name = "client_id", nullable = false)
	private Client client;

	/**
	* Constructs a portfolio without specifying an ID.
	* 
	* @param creationDate, the creation date of the portfolio.
	* @param securities, the list of securities in the portfolio.
	* @param client, the client associated with the portfolio.
	*/
	public Portfolio(String creationDate, List<Security> securities, Client client) {
		this.creationDate = creationDate;
		this.securities = securities;
		this.client = client;
	}
	
	/**
	*Constructs a portfolio only with an ID
	*@param portfolioId the unique identifier of the portfolio.
	*/
	public Portfolio(Long portfolioId) {
		this.portfolioId = portfolioId;
	}
}