package com.wellsfargo.counselor.entity;

import java.math.BigDecimal;

import com.wellsfargo.counselor.utils.SecurityType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/** 
 * Represents a financial security within the counselor system.
 *   
 * <p>
 * A {@code Security} stores details about individual financial instruments,
 * including name, category, purchasePrice, purchaseDate, quantity, and the
 * portfolio to which it belongs.
 *</p> 
 *
 *<p>
 *This entity is mapped to the {@code security} table in the database.
 *</p>
*/
@Entity
@Table(name = "security")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Security {

	/**
	 * Unique identifier for the security, auto-generated by the database.
	*/
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "security_id")
	private Long securityId;

	/** Name of the security. */
	@NotBlank
	@Column(name = "name",nullable = false)
	private String name;
	
	/**	Category of the security. */
	@NotNull
	@Column(name = "category", nullable = false)
	private String category;
	
	/**	Purchase price of the security. */	
	@NotNull
	@Column(name = "purchase_price",nullable = false)
	private BigDecimal purchasePrice;
	
	/**
	 * Purchase date of the security.
	 * <p>
	 * Stored as a String for flexible type conversion. Format YYYY-MM-DD.
	 * </p>
	*/
	@NotBlank
	@Column(name = "purchase_date",nullable = false)
	private String purchaseDate;
	
	/** Quantity of the security purchased. */	
	@NotNull
	@Column(name = "quantity",nullable = false)
	private Integer quantity;
	
	/**
	 * Portfolio associated with the security.
	 * <p>
	 * Represents many-to-one relationship; multiple securities can belong to a single portfolio.
	 * </p> 
	 */
	@ManyToOne
	@JoinColumn(name = "portfolio_id")
	private Portfolio portfolio;
	
	/**
	 * Constructs the securities without specifying an ID.
	 * 
	 * @param name the name of the security
	 * @param category the category of the security
	 * @param purchasePrice the purchase price of the security
	 * @param purchaseDate the purchase date of the security
	 * @param quantity the number of units purchased
	 * @param portfolio the portfolio associated with this security
	*/
	public Security(String name, String category, BigDecimal purchasePrice,
					String purchaseDate, Integer quantity,Portfolio portfolio) {
			this.name = name;
			this.category = category;
			this.purchasePrice = purchasePrice;
			this.purchaseDate = purchaseDate;
			this.quantity = quantity;
			this.portfolio = portfolio;
		}
	}